export { default as HeroOverlay } from './structure/HeroOverlay.vue'
export { default as HeroCoverMedia } from './structure/HeroCoverMedia.vue'
export { default as HeroIdentity } from './structure/HeroIdentity.vue'
export { default as HeroBadge } from './structure/HeroBadge.vue'
export { default as HeroBadges } from './structure/HeroBadges.vue'
export { default as HeroDescription } from './structure/HeroDescription.vue'
export { default as HeroActions } from './structure/HeroActions.vue'
export { default as HeroLogo } from './structure/HeroLogo.vue'

export { default as HeroClassic } from './HeroClassic.vue'
export { default as HeroCentered } from './HeroCentered.vue'
export { default as HeroOverlayVariant } from './HeroOverlayVariant.vue'
export { default as HeroSplit } from './HeroSplit.vue'
export { default as HeroMinimal } from './HeroMinimal.vue'
export { default as HeroBusiness } from './HeroBusiness.vue'
export { default as HeroFloating } from './HeroFloating.vue'
export { default as HeroFullBleed } from './HeroFullBleed.vue'
